apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kirogate-ingress
  namespace: kirogate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kirogate.yourdomain.com
      secretName: kirogate-tls
  rules:
    - host: kirogate.yourdomain.com
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
